name = "NonlinearNormalForm"
uuid = "05e19671-dec8-4f15-984f-54eaa6ca64be"
authors = ["Matt Signorelli"]
version = "1.0.0-DEV"

[deps]
GTPSA = "b27dd330-f138-47c5-815b-40db9dd9b6e8"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
